config/routes.rb
Rails.application.routes.draw do

root 'authentication#user_screen'

  
  get 'user_login', to: 'authentication#user_login'
  get 'callback',   to: 'authentication#callback'
  resources :photosets, only: [:index]
  get  'photos', to: 'photos#index'
  post 'photos', to: 'photos#index'
  get  'photos_show', to: 'photos#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= session[:user_id]    
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  CALLBACK_URL = "http://127.0.0.1:3000/callback" if Rails.env.development?
  CALLBACK_URL = "http://flkrshare.herokuapp.com/callback" if Rails.env.production?

  def user_login
    username = params[:username]
    user = flickr.people.findByUsername(username: username)
    session[:user_id]  = user["id"]
    session[:username] = username
    token = flickr.get_request_token(oauth_callback: CALLBACK_URL)
    Rails.cache.write("oauth_token", token['oauth_token'])
    Rails.cache.write("oauth_token_secret", token['oauth_token_secret'])
    session[:oauth_token]        = token['oauth_token']  
    session[:oauth_token_secret] = token['oauth_token_secret']
    auth_url = flickr.get_authorize_url(token['oauth_token'], :perms => 'read')
    redirect_to auth_url
  end

  def callback
    oauth_verifier = params[:oauth_verifier]
    begin
      @access_token = flickr.get_access_token(Rails.cache.read("oauth_token"), Rails.cache.read("oauth_token_secret"), oauth_verifier)      
      # @access_token = flickr.get_access_token(session[:oauth_token], session[:oauth_token_secret], oauth_verifier)      
      flash[:success] = "This application already has permission from Flickr to access #{@access_token["username"]}'s original size photos."
      redirect_to photosets_path
    rescue FlickRaw::FailedResponse => e
      flash[:error] =  "Authentication failed : #{e.msg}"
      redirect_to root_path
    end 
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    photoset_id = params[:id]
    photos_hash = flickr.photosets.getPhotos(photoset_id: photoset_id, extra: "original_format")
    @total_number_of_photos = photos_hash.total
    @photoset_title = photos_hash.title
    @photos_array = photos_hash.photo    # extract the elements of key "photo" belongs to the photoset as an array
    add_isselected_to_photos_array
    Rails.cache.write("photos_array", @photos_array.to_a) # transform from FlickRaw::Response to array, and write to cache 
  end

  def show
    @photos_array  = Rails.cache.read("photos_array")
  end

  private

  def add_isselected_to_photos_array
    @photos_array.each {|h| h.to_hash["isselected"] = false } # h.class => FlickRaw::ResponseList, .to_hash transform to hash. 
  end

end    

app/controllers/photosets_controller.rb
class PhotosetsController < ApplicationController
  def index
    # user_id = flickr.people.findByUsername(username: current_user)
    @photosets = flickr.photosets.getList(user_id: session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def get_total_in_a_photoset(photosets, photoset_id)
  #   photosets.getPhotos(photoset_id: photoset_id).total
  # end

  # Photo Source URLs

  # The URL takes the following format:
  
  # http://farm{farm-id}.staticflickr.  com/{server-id}/{id}_{secret}.jpg
  #   or
  # http://farm{farm-id}.staticflickr.  com/{server-id}/{id}_{secret}_[mstzb].jpg
  #   or
  # http://farm{farm-id}.staticflickr.  com/{server-id}/{id}_{o-secret}_o.( jpg|gif|png)
  # * Before November 18th, 2011 the API  returned image URLs with hostnames like:   "farm{farm-id}.static.flickr.com". Those  URLs are still supported.
  
  # Size Suffixes
  
  # The letter suffixes are as follows:
  
  # s small square 75x75
  # q large square 150x150
  # t thumbnail, 100 on longest side
  # m small, 240 on longest side
  # n small, 320 on longest side
  # - medium, 500 on longest side
  # z medium 640, 640 on longest side
  # c medium 800, 800 on longest side†
  # b large, 1024 on longest side*
  # o original image, either a jpg, gif or  png, depending on source format

  WIDTH = '1024' # 720
  HEIGHT = '' # 480

  def generate_image_source(is_photoset, photo)
    # photo is a hash
    
    set_elements(is_photoset, photo)
    src  = "http://farm#{@farm}.static.flickr.com/#{@server}/#{@id}_#{@secret}#{@size}.jpg"
  end

  def generate_share_string(photo)
    set_elements(false, photo)
    shared_string = "<a herf='https://www.flickr.com/photos/chaoyee/#{@id}' title='#{@title}'><img src='https://farm#{@farm}.static.flickr.com/#{@server}/#{@id}_#{@secret}#{@size}.jpg' width=#{WIDTH} height=#{HEIGHT} alt='#{@title}'></a>"
  end

  private

  def set_elements(is_photoset, photo)
    # is_photoset    = photo['id'].length == 10 ? false : true

    @server        = photo["server"]
    @farm          = photo["farm"]
    @id            = is_photoset ? photo["primary"] : photo["id"]
    @secret        = photo["secret"]
    @title         = photo["title"] 
    @size          = is_photoset ? "_s"        : "_z"  
  end

end

app/helpers/layout_helper.rb
module LayoutHelper
  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.1.1"
  end
end

app/views/authentication/callback.html.erb
<!-- This page is obsolete. -->
<h3><%= "This application already has permission from Flickr to access #{@access_token["username"]}'s original size photos." %></h3>

<%= link_to 'Next', photosets_path, class: "btn btn-primary"%>

app/views/authentication/user_screen.html.erb
<div class="page header">
  <h3>Please input your user name:</h3>
</div>
<div class="well">
  <%= form_tag("/user_login", method: "get") do %>
    <%= label_tag(:username, "User Name:") %>
    <%= text_field_tag(:username) %>
    <%= submit_tag("Login", class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%=name%>" >
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flkrshare: Flickr sharing urls generator</title>
  <!-- bootstrap CDN -->
  <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet"> --> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#">Photo Management System</a> -->
          <%= link_to "Flickr sharing urls generator", root_path, :class => 'navbar-brand' %>
          <%#= render 'layouts/navigation' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>
  <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
          <div class="container">
            <div class="row">
              @Flicker Share, 2014
            </div>  
          </div>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>  
  <!-- bootstrap CDN -->
  <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>-->
</body>
</html>

app/views/photos/index.html.erb
<div class="page header">
  <h3>Total <%= @total_number_of_photos %> photos in "<%= @photoset_title %>"</h3>
  <%= link_to 'Generate sharing string!', photos_show_path, method: :get, class: 'btn btn-primary pull-right' %>
</div>
<br/>
<br/>
<div class="well table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Check it!</th>
        <th>Title</th>
        <th>ID</th>
        <th>Photo</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @photos_array.each do |photo| %>
        <tr>
          <td><%= check_box_tag(photo.id, photo["isselected"]) %></td>
          <td><%= photo.title %></td>
          <td><%= photo.id %></td>
          <td><%= image_tag(generate_image_source(false, photo), class: "img-thumbnail img-responsive") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

app/views/photos/show.html.erb
<div class="page header">
  The sharing strings are:
</div>  
<div class="well">
  <% @photos_array.each do |photo| %>
    <%= generate_share_string(photo) %>
    <%= "<br/>" %>
    <br/>
  <% end %>
</div>

app/views/photosets/index.html.erb
<div class="page header">
  <h2>Listing Flickr photosets</h2>
</div>
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="well table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Photo</th>
              <th>Title</th>
              <th>Description</th>
              <th>Id</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @photosets.each do |photoset| %>
              <tr>
                <td><%= link_to image_tag(generate_image_source(true, photoset)), photos_path(id: photoset.id), method: :post %></td>
                <td><%= photoset.title %></td>
                <td><%= photoset.description %></td>
                <td><%= photoset.id %></td>
                <td><%= link_to 'Select', photos_path(id: photoset.id), method: :post, class: 'btn btn-primary' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>       
    </div>
  </div>
</div> <!--! end of .container -->